language: node_js
node_js:
  - "stable"
before_install:
  - npm install -g jshint
  - npm install -g chrome-webstore-manager
after_success:
  - WEBSTORE_TOKEN=$(chrome-webstore-manager refresh_token --client_id $CLIENT_ID --client_secret $CLIENT_SECRET --refresh_token $REFRESH_TOKEN)
  - chrome-webstore-manager update $EXTENSION_ID ./build/rallyrap.zip
