language: node_js
node_js:
  - "stable"
before_install:
  - npm install -g fs
  - npm install -g archiver
  - npm install -g jshint
  - npm install -g chrome-webstore-manager
script:
  - npm run build
  - npm test
after_success:
  - chrome-webstore-manager update -t $(chrome-webstore-manager refresh_token --client_id $CLIENT_ID --client_secret $CLIENT_SECRET --refresh_token $REFRESH_TOKEN) $EXTENSION_ID ./build/rallyrap.zip
